# Generated by Django 2.2.4 on 2020-12-17 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='images/')),
                ('result_file', models.ImageField(blank=True, upload_to='images/')),
                ('readiness', models.CharField(default='0', max_length=1)),
                ('date_of_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
